excluded:
  - BookPlayer/Generated/AutoMockable.generated.swift
cyclomatic_complexity:
  ignores_case_statements: true
# line_length: 120
disabled_rules:
  - todo
  - line_length
  - type_name
  - switch_case_alignment
  - identifier_name
  - trailing_comma
  - private_over_fileprivate
  - force_try
  - type_body_length
  - file_length
  - orphaned_doc_comment
