name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    # https://github.com/actions/runner-images/tree/main/images/macos
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Create Debug.xcconfig
      run: cp ./BuildConfiguration/Debug.template.xcconfig ./BuildConfiguration/Debug.xcconfig
    - name: Swiftlint
      run: swiftlint
    - name: Resolve dependencies
      run: xcodebuild -resolvePackageDependencies
    - name: Build and Run tests
      run: xcodebuild -scheme BookPlayer test -testPlan Unit\ Tests -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0'

